site_name: Proyecto Final
dev_addr: 127.0.0.1:8002
# site_url: 
# repo_url: 
# repo_name: <i class="fa fa-git"></i>

theme:
    name: mkdocs
    custom_dir: resources/
extra_css:
    - css/page.css
nav:
    - Problema: TRAB.md
    - Requerimientos:
        - Requerimientos Usuario: requerimientos/REQUSU.md
        - Requerimientos Sistema: requerimientos/REQSIS.md
    - Diseño:
        - Inicio: diseño/DIS.md
    - Validación:
        - Métricas: pruebas/pru.md
        - Pruebas unitarias: pruebas/PRUN.md
        - Pruebas de integración: pruebas/PRI.md
copyright: ©GMDXX
site_author: GMDXX
